-- Run this in Supabase SQL Editor.
-- Security model: browser uses ONLY the public publishable/anon key.
-- Never expose service_role/secret keys in frontend code.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_name text not null,
  amount numeric(12,2) not null check (amount >= 0),
  payment_reference text,
  status text not null default 'pending' check (status in ('pending','approved','declined')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;

-- Least-privilege grants.
revoke all on public.profiles from anon, authenticated;
revoke all on public.orders from anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update on public.orders to authenticated;
grant usage, select on sequence public.orders_id_seq to authenticated;

-- SECURITY DEFINER is used only for role lookup. Fixed search_path is important.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin') $$;

create policy "profile own or admin read" on public.profiles for select to authenticated
using (id=(select auth.uid()) or public.is_admin());

create policy "customer inserts own order" on public.orders for insert to authenticated
with check (user_id=(select auth.uid()) and status='pending');

create policy "customer reads own orders or admin reads all" on public.orders for select to authenticated
using (user_id=(select auth.uid()) or public.is_admin());

create policy "admin updates orders" on public.orders for update to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Create profile safely from Auth data.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,full_name,email,role)
  values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.email,''),'customer')
  on conflict(id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- After YOU create your account, replace the UUID and run once:
-- update public.profiles set role='admin' where id='YOUR_AUTH_USER_UUID';
